### PR TITLE
Implement PVR addon API v6.0.0

### PR DESCRIPTION
**Pull request by ksooo**
Initial Kodi Matrix Addon version, implements PVR addon API v6.0.0

Do not merge until https://github.com/xbmc/xbmc/pull/15953 was merged!

### CODE REVIEW

**Review by rbuehlma — APPROVED** [review]

**Comment by rbuehlma** [comment]
Shouldn't this change go into master branch?

**Comment by ksooo** [comment]
> Shouldn't this change go into master branch?

 No.

 PVR Addon "Leia" branch -> Kodi "Leia" branch
 PVR Addon "Matrix" branch -> Kodi "master" branch
 PVR Addon "master" branch -> dead

 We need to "shadow" the binary addon repo structure with the addon branch. Binary addon repo "master" would be ambigious.

**Comment by ksooo** [comment]
fyi. => https://github.com/palinek/pvr.sledovanitv.cz/pull/29#issuecomment-486096685

**Comment by rbuehlma** [comment]
> fyi. => [palinek/pvr.sledovanitv.cz#29 (comment)](https://github.com/palinek/pvr.sledovanitv.cz/pull/29#issuecomment-486096685)

Done, Matrix is now default and master gone.

**Pull request merged**
