### PR TITLE
[depends] move sqlite3 to depends

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by rbuehlma** [comment]
@Rechi since the builds are green, shall I merge it?

**Comment by Rechi** [comment]
You are the maintainer, you have to decide.
I can only tell you, that adding sqlite3 to depends is the only correct way for using it.

**Comment by rbuehlma** [comment]
I'm not used to cmake and its dependency management and  therefore need to rely on the input from others. Thanks for this cleanup.

**Comment by Rechi** [comment]
This is not about CMakes dependencies management.
You forced everyone, even Linux distributions, to use the copy of sqlite3 in your git repo.

**Pull request merged**
