### PR TITLE
[Matrix] API update

### PR DESCRIPTION
**Pull request by AlwinEsch**
API related to xbmc/xbmc#17438 (DEMUX_PACKET not used there)

### CODE REVIEW

**Comment by rbuehlma** [comment]
@AlwinEsch what is the idea behind this change? As far as I know, the version should not have any technical impact?

And should it already be merged?

**Comment by AlwinEsch** [comment]
Is to merge after the request on Kodi is in, there is on inputstream addon a change to have it correct in "C" and with some fixes about memleaks.

Problem about PVR is that there the DemuxPacket from inputstream still is used and PVR API has then also needed a version increase.

DemuxPacket before was C++ struct and also with C++11 shared ptr inside, there we can not sure that always correct if addon and Kodi compiled with different compiler versions.

**Comment by AlwinEsch** [comment]
The request on Kodi comes in 1-2 days in and update also here needed.

**Comment by AlwinEsch** [comment]
About Ubuntu a new release with 19.5.1 is needed! This request was come in to early and his binary created there with old Kodi version.

His build is here e.g. https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly/+build/20218905 only not usable with current Kodi there.

**Comment by rbuehlma** [comment]
Rebuild is triggered. Thanks for the hint.

**Pull request merged**
